### ISSUE TITLE
Upgrade Node.js version from 16 to 18

### ISSUE THREAD

**Issue by mziyut** [increments/camo#11]
## What

- Upgrade Node.js version from 16 to 18

https://github.com/increments/camo/blob/13d295f8bea4f7cf05f08a8890b5b950faac887b/Dockerfile#L1

### Goals

- Using Node.js v18

### Non-Goals

- Node.js version 19 support

## References

- https://github.com/increments/camo/pull/10
- [nodejs/Release: Node.js Release Working Group](https://github.com/nodejs/release#release-schedule)

**Comment by tomoasleep** [comment]
done by https://github.com/increments/camo/pull/13
